"""add transaksi

Revision ID: 2402e55abf87
Revises: 
Create Date: 2025-08-19 14:06:35.052248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2402e55abf87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barang_id', sa.Integer(), nullable=True),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('total_harga', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['barang_id'], ['barang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaksi_id'), 'transaksi', ['id'], unique=False)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.drop_index(op.f('ix_transaksi_id'), table_name='transaksi')
    op.drop_table('transaksi')
    # ### end Alembic commands ###
